### ISSUE TITLE
sanitizeConfig Error (Vue & TS)

### ISSUE THREAD

**Issue by ewalpole** [codex-team/editor.js#1952]
Working on a very simple/basic implementation using Vue 2.0 & TS and I am getting a sanitize config error when the Editor is trying to save as I add each text block. Am I missing something on the config where I should be setting the sanitizer?

Thanks!

```
editor.js:2 Editor.js 2.22.2 Saving failed due to the Error TypeError: Cannot read properties of undefined (reading 'sanitizeConfig')
    at editor.js:2:1
    at Array.forEach (<anonymous>)
    at o.get (editor.js:2:1)
    at o.n.<computed> (editor.js:2:1)
    at o.get (editor.js:2:1)
    at o.n.<computed> (editor.js:2:1)
    at editor.js:2:1
    at editor.js:2:1
    at Array.map (<anonymous>)
    at t.sanitizeBlocks (editor.js:2:1) %o
```

```
import EditorJS from '@editorjs/editorjs';
import Header from '@editorjs/header';
import List from '@editorjs/list';
import Underline from '@editorjs/underline';
import EditorJSToHTML from 'editorjs-html';
import type { API, BlockAPI, LogLevels, OutputData, SanitizerConfig } from '@editorjs/editorjs/index';

    createEditor(): void {
      this.htmlParser = new EditorJSToHTML();
      this.editor = new EditorJS({
        holder: this.holder,
        autofocus: this.autofocus,
        onReady: this.onReady,
        onChange: this.onChange,
        inlineToolbar: ['header', 'bold', 'italic', 'underline', 'list'],
        tools: {
          header: {
            class: Header,
            inlineToolbar: true,
          },
          list: {
            class: List,
            inlineToolbar: true,
          },
          underline: {
            class: Underline,
            inlineToolbar: true,
          },
        },
      });
    },

   onReady(): void {
      this.isReady = true;
    },
    async onChange(api: API, block: BlockAPI): Promise<void> {
      const response = await api.saver.save();
      console.log('Article data: ', response as OutputData);   // this is coming out as undefined
    },

```

**Comment by neSpecc** [comment]
Looks like you are trying to use the Header Block tool and the List Block tool as an Inline tools.

Change this

```
inlineToolbar: ['header', 'bold', 'italic', 'underline', 'list'],
```

To this

```
inlineToolbar: ['bold', 'italic', 'underline'], 
```

**Comment by ewalpole** [comment]
@neSpecc thanks for catching that, will fix it and get back on if it's working now.

**Comment by ewalpole** [comment]
That fixed it, thanks for the help!
