### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'onFocus')

### ISSUE THREAD

**Issue by cptiwari20** [codex-team/editor.js#2399]
Describe a bug.
Uncaught TypeError: Cannot read properties of undefined (reading 'onFocus'), shows up when I hit tab button on the editor js or some other keys while selecting the items

Expected behavior:
It should focus on the selected content or block, It does sometimes but not.
How can I handle such unexpected errors?

Error Message:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'onFocus')
    at onFlip (editorjs.mjs:3729:1)
    at editorjs.mjs:3592:1
    at Array.forEach (<anonymous>)
    at G.flipCallback (editorjs.mjs:3592:1)
    at G.flipRight (editorjs.mjs:3523:1)
    at G.onKeyDown (editorjs.mjs:3462:1)

```
![image](https://github.com/codex-team/editor.js/assets/33618258/44460f58-1e24-4538-8d0a-8c8b5eb0ebae)

Device, Browser, OS: Windows/MacOs

Editor.js version: 2.26.2

Plugins you use with their versions:
 "@editorjs/checklist": "^1.4.0",
    "@editorjs/delimiter": "^1.3.0",
    "@editorjs/editorjs": "^2.26.2",
    "@editorjs/embed": "^2.5.3",
    "@editorjs/header": "^2.7.0",
    "@editorjs/image": "^2.8.1",
    "@editorjs/inline-code": "^1.4.0",
    "@editorjs/link": "^2.5.0",
    "@editorjs/marker": "^1.3.0",
    "@editorjs/nested-list": "^1.3.0",
    "@editorjs/paragraph": "^2.9.0",
    "@editorjs/quote": "^2.5.0",
    "@editorjs/raw": "^2.4.0",
    "@editorjs/table": "^2.1.2",
    "@editorjs/warning": "^1.3.0",

**Comment by neSpecc** [comment]
Can't reproduce. Please, use the latest editor.js version and provide a demo where we can reproduce the problem

**Comment by ShebangDog** [comment]
same

In my case, I opened Blocktune and moved the cursor on it. Then, the application displayed an error.

**Comment by ShebangDog** [comment]
Sorry, I resolved it.
I forgot to use renderSettings instead of settings.

So i use renderSettings for rendering settings, then it resolved

before
```
class Paragraph extends ParagraphToolEditor {
...
constructor() {
  this.settings = [ /* setting-styles */ ]
}
}
```

after
```
class Paragraph extends ParagraphToolEditor {
...
  renderSettings() {
    return [ /* settings-styles */ ]
  } 
}
```

refs: https://editorjs.io/tools-api/#rendersettings
